from sudoku_solver.structures import e

board_values_by_difficulty = {
    'easy1': (
        (e, 1, e, e, 9, 6, 8, 3, e),
        (9, 3, e, 2, e, e, e, 4, e),
        (8, 2, 4, 7, e, 3, 1, e, e),
        (e, e, 5, 9, e, e, e, e, e),
        (6, e, e, e, 8, 5, 4, 2, 9),
        (2, e, 8, e, e, 4, e, 6, 1),
        (7, e, e, e, 3, e, e, 8, e),
        (e, e, e, 8, e, e, e, e, 3),
        (e, e, 1, e, 4, 9, 2, e, 7),
    ),
    'medium1': (
        (6, 4, e, e, e, e, 2, 3, e),
        (9, e, 2, 6, e, e, e, e, e),
        (e, e, e, 2, 8, e, 4, e, 6),
        (e, 2, 6, 7, e, e, e, 1, 5),
        (e, e, e, 1, e, e, 3, e, e),
        (1, e, e, e, 9, e, 6, 8, e),
        (e, 9, e, e, 1, 7, e, e, e),
        (8, 6, 4, e, e, e, 1, 7, 9),
        (e, 1, e, e, e, e, e, e, e),
    ),
    'medium2': (
        (e, 3, e, e, 1, e, e, e, e),
        (e, e, e, 9, e, e, 2, e, 8),
        (e, e, 6, e, 2, 4, e, e, 3),
        (e, e, 1, e, 9, 8, 3, e, e),
        (3, 7, 8, e, e, e, e, e, e),
        (4, e, e, 6, e, 3, 1, e, e),
        (9, 8, e, e, e, e, e, e, e),
        (e, e, e, 4, 5, 9, e, e, 7),
        (2, 5, e, e, e, e, e, 4, 9),
    ),
    'hard1': (
        (e, e, 8, e, e, e, e, e, e),
        (e, 4, e, e, e, 5, e, 7, e),
        (6, e, 1, e, e, e, e, 9, 8),
        (e, e, 4, e, 3, e, e, e, 2),
        (e, 2, e, 6, e, 9, 3, 8, e),
        (1, e, e, e, 2, 7, e, e, e),
        (4, e, 5, e, e, e, e, e, 6),
        (e, e, e, 4, 9, e, 5, 1, e),
        (e, e, e, e, e, 3, e, 2, e),
    ),
    'hard2': (
        (e, e, e, e, e, e, 5, e, 6),
        (e, e, 5, e, 8, e, e, e, 4),
        (e, e, 3, 2, e, e, 1, e, e),
        (e, e, 2, e, 7, e, e, e, e),
        (e, 6, 4, 5, e, e, 2, e, e),
        (e, 9, e, 1, e, e, e, e, e),
        (8, 7, e, 3, e, 5, e, e, e),
        (e, 4, e, e, 2, 6, e, e, 5),
        (e, e, e, e, e, e, 4, e, e)
    ),
    'hard3': (
        (e, e, 8, 1, e, 2, e, e, e),
        (e, e, e, e, e, e, e, e, 6),
        (2, e, e, 7, e, 4, 5, e, 3),
        (e, e, 6, e, e, e, 9, e, 1),
        (e, 2, e, e, e, 5, 6, e, e),
        (1, 7, 9, e, e, 3, e, e, e),
        (4, e, e, e, 5, e, e, 1, e),
        (e, e, e, e, e, e, e, e, e),
        (e, 6, e, e, e, e, 3, e, 4),
    ),
    'expert1': (
        (e, 2, 7, 5, e, e, e, e, e),
        (e, e, e, e, e, 3, e, e, e),
        (e, e, e, 6, e, e, 9, e, 4),
        (4, e, e, 1, e, e, e, e, e),
        (e, e, e, e, e, e, 7, e, e),
        (e, 5, e, e, e, e, e, 9, 6),
        (e, 7, e, 9, e, e, e, 6, e),
        (1, e, 5, e, e, e, e, e, e),
        (9, e, e, 4, e, e, 3, e, 8),
    ),
    'not_solvable1': (
        (e, 7, e, e, 4, e, e, 5, e),
        (e, 9, 4, 7, 6, e, e, e, 1),
        (e, 6, e, e, e, e, e, 2, e),
        (5, e, e, e, 7, e, e, 1, e),
        (e, e, e, e, e, e, e, 3, e),
        (e, 4, e, e, 8, e, 9, e, e),
        (e, e, e, 2, e, 6, e, e, e),
        (4, e, e, e, e, 8, e, e, 2),
        (3, e, e, e, 1, e, e, 8, e),
    )
}
